/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface _DrizzleMigrations {
  created_at: number | null;
  hash: string;
  id: string | null;
}

export interface Companies {
  company_type: string | null;
  created_at: Generated<number>;
  description: string | null;
  enrichment_status: Generated<string>;
  id: Generated<number>;
  name: string;
  normalized_name: Generated<string>;
  updated_at: Generated<number>;
}

export interface Jobs {
  company: string;
  created_at: Generated<number>;
  description: string;
  experience_level: string | null;
  id: Generated<number>;
  job_url: string;
  location: string;
  posted_date: number;
  salary: string | null;
  source: string;
  technologies: string | null;
  title: string;
  updated_at: Generated<number>;
  work_arrangement: string | null;
}

export interface JobTechnologies {
  created_at: Generated<number>;
  id: Generated<number>;
  job_id: number;
  technology_id: number;
}

export interface Locations {
  created_at: Generated<number>;
  id: Generated<number>;
  name: string;
}

export interface NormalizedJobs {
  company_id: number;
  created_at: Generated<number>;
  description: string;
  enriched_at: number | null;
  enrichment_attempts: Generated<number>;
  enrichment_error: string | null;
  enrichment_status: Generated<string>;
  id: Generated<number>;
  is_relevant: Generated<number>;
  job_url: string;
  location_id: number;
  posted_date: number;
  salary_text: string | null;
  scraped_job_id: number;
  seniority_level: string | null;
  source: string;
  title: string;
  updated_at: Generated<number>;
  work_arrangement: string | null;
}

export interface ScrapedJobs {
  id: Generated<number>;
  job_url: string;
  processed: Generated<number>;
  raw_data: string;
  scraped_at: Generated<number>;
  source: string;
}

export interface Technologies {
  category: string | null;
  created_at: Generated<number>;
  id: Generated<number>;
  name: string;
}

export interface DB {
  __drizzle_migrations: _DrizzleMigrations;
  companies: Companies;
  job_technologies: JobTechnologies;
  jobs: Jobs;
  locations: Locations;
  normalized_jobs: NormalizedJobs;
  scraped_jobs: ScrapedJobs;
  technologies: Technologies;
}
